// Agent: Code Generator — 최종 JSON 으로 독립 page.tsx 코드 스냅샷 산출 (GOAL.md 정식 해석: 부).
// 실제 렌더는 데이터 기반(/preview/[runId]). 이 산출물은 "Generated Code" 아티팩트.
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { LandingReferenceAnalysis } from "../schema";

function renderPageSource(analysis: LandingReferenceAnalysis): string {
  const json = JSON.stringify(analysis, null, 2);
  return `// AUTO-GENERATED by "Landing Page from Reference" — data-driven snapshot.
// 최종 분석 JSON 을 공유 렌더러로 렌더하는 독립 Next 페이지입니다.
// 원본 레퍼런스 자산은 복사하지 않으며, 구조/스타일 토큰만 재해석합니다.
import { LandingRenderer } from "@/components/LandingRenderer";
import type { LandingReferenceAnalysis } from "@/lib/schema";

const analysis: LandingReferenceAnalysis = ${json};

export default function GeneratedLanding() {
  return <LandingRenderer analysis={analysis} />;
}
`;
}

export async function generatePageCode(
  runId: string,
  analysis: LandingReferenceAnalysis,
): Promise<{ codePath: string; code: string }> {
  const code = renderPageSource(analysis);
  const dir = join(process.cwd(), "runs", runId, "generated");
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, "page.tsx"), code, "utf8");
  await writeFile(join(dir, "analysis.json"), JSON.stringify(analysis, null, 2), "utf8");
  return { codePath: `runs/${runId}/generated/page.tsx`, code };
}
